### ISSUE TITLE
Error with ukb_df

### ISSUE THREAD

**Issue by hilge** [kenhanscombe/ukbtools#1]
Hi Ken.

(Hope you are well. You may remember me from the SGDP, years back we had a few processing meetings, with Oliver)

I am keen to try your biobank tool out, but when I run the ukb_df command I get the following error:

> my_ukb <- ukb_df("ukbXXXX")
Error in source(if (path == ".") { :
  /mnt/10tbstore/projects/ukb/ukbXXXX.r:219:18: unexpected symbol
218: lvl.100391 <- c(-3,-1,1,2,3,4)
219: lbl.100391 <- c("Prefer

I looked for changes in the ukbXXXX.r file before and after I ran ukb_df and can see that there is some weird substitution going on at line 219.

Before the command ukbXXXX.r looks like this on line 214:
lbl.100388 <- c("Prefer not to answer","Do not know","Never/rarely use spread","Butter/spreadable butter","Flora Pro-Active/Benecol","Other type of spread/margarine")

After the command the same line is a bit further down on line 219 and the path have been added in a wierd way:
lbl.100388 <- c("Prefer not to answer","Do not know","Never/rarely use spread.delim('/mnt/10tbstore/projects/ukb/ukbXXXX.tab')

Any ideas what may be causing this?
All the best,
Johan

**Comment by kenhanscombe** [comment]
Hi Johan,

Hope you're well.

Thanks for catching this. It looks like my regular expression to update the path was too general: "read.*$" picked up Spread. Please try re-install the latest develop version v0.10.1 where I have fixed this.

devtools::install_github("kenhanscombe/ukbtools", build_vignettes = TRUE, dependencies = TRUE, force = TRUE)

I'm assuming you are correctly replacing XXXX with the specific id of your approved data? (not clear if you've just changed to XXXX in example to mask your study id). To read ukb4321.r, ukb4321.tab, ukb4321.html

use,

ukb_df("ukb4321")

Also, if the .r, .tab, and .html files are not in the current directory (and/or if they have been moved from the directory in which you first created them), you need to specify the full path, with the path argument. ukb_df should only update the path to the .tab file in the ukb_conv generated script .r

If your .r file appears to have any odd changes, I'd recommend deleting and recreating it (with UKB's ukb_conv) before re-running ukb_df 

Let me know if this works and I'll include it in the next CRAN update.

Ken

**Comment by hilge** [comment]
Hi Ken
That fixed the problem. I have still not finished running the ukb_df command though, my issue now is that it seems the process needs a minimum of 16Gb memory, I have been running it locally on a machine with 8Gb, and that starts putting a lot of stuff into SWAP memory. I was trying to run it just now on our cluster but ran into problems installing your packages (problems relating to the cluster and not your package as such) I should be able to get this sorted though and will let you know when I have been able to run the command to the end. 

Thanks for you quick reply by the way.
PS: Yes I saw you had anonymised the file name so I thought I would do the same in my example, even though I properly don’t need to anonymise our project ID code as such :-)
Best,
Johan

**Comment by kenhanscombe** [comment]
Hi Johan,

My local setup is 8 GB 1600 MHz DDR3.

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Took about 8 minutes to read a file set with 2.6GB tab file (loading the same dataset after the save() to binary, took < 20 secs). How big is your tab file?

**Comment by hilge** [comment]
My tab file is 9.3GB which may be causing the difference. After about 2 min the mermory is all used up and goes into SWAP and then everything slows down. I have not actually tried running it to the end, but left it for an houre at some point and it had not finished, and then I stoped the job as everything was so slow.

**Comment by kenhanscombe** [comment]
That's pretty big. Try re-install the latest dev version, I've changed the read function and assigned column types from the html file. Although, I doubt this will solve the problem.

I'll try to implement a chunked read when I get some time.

In the meantime, a possible work-around could be to split up your tab file before reading it into R. You will have to make a corresponding copy of the r and html files for each split; e.g. ukbXXXX.tab, ukbXXXX.r, ukbXXXX.html into

ukbXXXX-1.tab, ukbXXXX-1.r, ukbXXXX-1.html
ukbXXXX-2.tab, ukbXXXX-2.r, ukbXXXX-2.html
ukbXXXX-3.tab, ukbXXXX-3.r, ukbXXXX-3.html
etc.

After reading each new fileset, you can stick them together with something like dplyr::bind_rows

**Comment by hilge** [comment]
Thanks Ken.
I did actually look at splitting the tab file up today, and that does solve it. I manage to get the furst chunk loaded as an R object, with the ukb_df function, so thats good. I will give your latest version a go as well, on the full file, and let you know if your new updates will let it read the full file on its own.

Thanks for you help with this.
J

**Comment by kenhanscombe** [comment]
Hi Johan,

How did you get on - did you manage to load and stitch all chunks? Is it ok with you if I close this issue and open a Project to implement a chunked read (and/ or include a file splitter module)?

All the best,

Ken

**Comment by hilge** [comment]
Hi Ken,

Yes I did manage to load and stitch everything together, so please close the issue.  I also ran your context command which worked as well.

Thanks for you help
Best,
Johan

**Comment by kenhanscombe** [comment]
Thanks, Johan. Let me know if there is any other functionality you think would be useful. I'll add the chunked read enhancement as a Project.

**Comment by mkapoor123** [comment]
Hello, Thank you for creating the ukbtools package. 
The current issue I am facing is 
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: './ukb26###.html'
I have moved all the files to the same drive, and re-converted the files using conv. 
Any ideas what may be causing this?
Thanks heaps, Mahima
